MachineLearning-Web/MachineLearning-Web/MachineLearging/src/br/com/ufc/ia/machinelearning/bean/AutocompleteBean.java
package br.com.ufc.ia.machinelearning.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.model.SelectItem;

import br.com.ufc.ia.machinelearning.enumeration.MethodEnum;


@ManagedBean(name="autocompleteBean") @SessionScoped
public class AutocompleteBean implements Serializable{
	
	private static final long serialVersionUID = 1L;

	public List<SelectItem> getListMethods(){
		List<SelectItem> list = new ArrayList<SelectItem>();
		for(MethodEnum method : MethodEnum.values()){
			list.add(new SelectItem(method.ordinal(), method.toString()));
		}
		return list;
	}

}

MachineLearning-Web/MachineLearning-Web/MachineLearging/src/br/com/ufc/ia/machinelearning/bean/MainBean.java
package br.com.ufc.ia.machinelearning.bean;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.primefaces.component.inputtext.InputText;
import org.primefaces.component.panel.Panel;
import org.primefaces.component.watermark.Watermark;
import org.primefaces.event.CellEditEvent;
import org.primefaces.model.UploadedFile;
import org.primefaces.model.chart.CartesianChartModel;
import org.primefaces.model.chart.ChartSeries;

import br.com.ufc.ia.machinelearning.enumeration.MethodEnum;
import br.com.ufc.ia.machinelearning.model.FileData;
import br.com.ufc.ia.machinelearning.spi.Algorithm;
import br.com.ufc.ia.machinelearning.spi.Point;
import br.com.ufc.ia.machinelearning.util.Mensagem;
import br.com.ufc.ia.machinelearning.util.Util;

@ManagedBean(name="mainBean") @ViewScoped
public class MainBean implements Serializable{

	private static final long serialVersionUID = 1L;

	private static final String INICIAL = "inicial";
	
	private Integer selectedMethod = null;
	private Integer selectedParameter = 1;
	private int selectedChartType = 1;
	
	private UploadedFile file;
	private List<FileData> listDataModel;
	private FileData newData = new FileData(0L);
	private FileData removedData;
	private Long newDataRowKey = 0L;
	private String nameColumn1;
	private String nameColumn2;
	private String fileSeparator = ",";
	
	private boolean showResults = false;
	private boolean showParameters = false;
	private boolean hasHeader = true;
	
	private Algorithm<List<Point>> algorithm;
	private List<Point> listResultPoints;
	private String output;
	private String objTest;

	private CartesianChartModel chartModel;
	private Panel panelParameters = new Panel();
	
	private MethodEnum method;
	
	public String prepareToShow(){
		showResults = false;
		hasHeader = true;
		fileSeparator = ",";
		return INICIAL;		
	}
	
	public void populateParameters(){
		if(selectedMethod != null && selectedMethod != -1){
			method = MethodEnum.values()[selectedMethod];
			if(method.getParametersNames().length > 0){
				showParameters = true;
				
				panelParameters.setHeader(method.toString() + " Parameters");
				panelParameters.getChildren().clear();
				for(int i = 0; i < method.getParametersNames().length; i++){
					String parameterName = method.getParametersNames()[i];
					parameterName = Util.normilizeId(parameterName);
					
					InputText input = new InputText();
					input.setId(parameterName);
					input.setStyleClass("parameterInput");
					
					Watermark watermark = new Watermark();
					watermark.setFor(parameterName);
					watermark.setValue(method.getParametersNames()[i]);
					
					panelParameters.getChildren().add(input);
					panelParameters.getChildren().add(watermark);
				}
			}
			else{
				showParameters = false;
				panelParameters.getChildren().clear();
			}
		}
		else{
			showParameters = false;
			panelParameters.getChildren().clear();
		}
	}
	
	@SuppressWarnings("unchecked")
	public void execute(){
		if(listDataModel == null || listDataModel.isEmpty()){
			Mensagem.sendErrorMessage("No data inserted", null);
			return;
		}
		if(selectedMethod == null || selectedMethod == -1){
			Mensagem.sendErrorMessage("No method selected", null);
			return;
		}
		chartModel = new CartesianChartModel();
		try {
			algorithm =  (Algorithm<List<Point>>) Class.forName("br.com.ufc.ia.machinelearning.algorithm."+method.getClassName()).newInstance();
			List<Point> listPoints = new ArrayList<Point>();
			for(FileData fileData:listDataModel){
				listPoints.add(new Point(fileData.getValue1(), fileData.getValue2()));
			}
			for(int i = 0; i < method.getParametersNames().length; i++){
				String parameter = Util.normilizeId(method.getParametersNames()[i]);
				algorithm.getParameters().addParam(parameter, ((InputText)panelParameters.getChildren().get(i*2)).getValue());
			}
			algorithm.execute(listPoints, null);
			listResultPoints = algorithm.getResult(); 
			output = algorithm.getReport().getAllReports();
			
			ChartSeries chartSerie = new ChartSeries();
			for(Point point : listResultPoints){
				chartSerie.set(point.x, point.y);
			}
			chartModel.addSeries(chartSerie);
			showResults = true;
			
		} catch (InstantiationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public void addData(){
		if(newData != null){
			newData.setId(newDataRowKey);
			if(listDataModel == null){
				listDataModel = new ArrayList<FileData>();
			}
			listDataModel.add(newData);
			newDataRowKey++;
			newData = new FileData(newDataRowKey);
		}
	}
	
	public void removeData(){
		if(removedData != null){
			listDataModel.remove(removedData);
			newDataRowKey++;
			removedData= null;
		}
	}
	
	public void loadFile(){
		if(file != null){
			try{
				byte[] uploadBytes = (byte[]) file.getContents();
				ByteArrayInputStream byteInputStream = new ByteArrayInputStream(uploadBytes);  
				InputStreamReader inputStreamReader = new InputStreamReader(byteInputStream);
				
				BufferedReader item = new BufferedReader(inputStreamReader); 
				String line;

				listDataModel = new ArrayList<FileData>();
				int numberOfColumns = 2;
				
				if(hasHeader){
					line = item.readLine();
					String nameColumns[] = line.split(fileSeparator,-1);
					if(nameColumns.length == numberOfColumns){
						nameColumn1 = String.valueOf(nameColumns[0]);
						nameColumn2 = String.valueOf(nameColumns[1]);
					}
				}
				Long i = 0L;
				while((line = item.readLine()) != null){
					String values[] = line.split(fileSeparator,-1);
					if(values.length == numberOfColumns){
						FileData fileData = new FileData(i);
						try{
							fileData.setValue1(Double.valueOf(values[0]));
							fileData.setValue2(Double.valueOf(values[1]));
							listDataModel.add(fileData);
						}
						catch(NumberFormatException e){
							Mensagem.sendErrorMessage("Invalid file data on line #"+(i+1)+"!", null);
							listDataModel = null;
							return;
						}
						i++;
					}
				}
				if(listDataModel != null){
					newDataRowKey = Long.valueOf(listDataModel.size());
				}
			}
			catch(IOException e){
				e.printStackTrace();
			}
		}
	}
	
	public void onCellEdit(CellEditEvent event){
		Object oldValue = event.getOldValue();  
        Object newValue = event.getNewValue();  
          
        if(newValue != null && !newValue.equals(oldValue)) {  
        	System.out.println("valor da celular modificado de "+ oldValue +" para "+ newValue + "!");
        }
	}
	
	public String getFileNameTruncated(){
		if(file != null){
			return Util.truncate(file.getFileName(), 20);
		}
		return null;
	}
	
	public UploadedFile getFile() {
		return file;
	}

	public void setFile(UploadedFile file) {
		this.file = file;
	}

	public List<FileData> getListDataModel() {
		return listDataModel;
	}

	public void setListDataModel(List<FileData> listDataModel) {
		this.listDataModel = listDataModel;
	}

	public String getNameColumn1() {
		return nameColumn1;
	}

	public void setNameColumn1(String nameColumn1) {
		this.nameColumn1 = nameColumn1;
	}

	public String getNameColumn2() {
		return nameColumn2;
	}

	public void setNameColumn2(String nameColumn2) {
		this.nameColumn2 = nameColumn2;
	}

	public Algorithm<List<Point>> getAlgorithm() {
		return algorithm;
	}

	public void setAlgorithm(Algorithm<List<Point>> algorithm) {
		this.algorithm = algorithm;
	}

	public List<Point> getListResultPoints() {
		return listResultPoints;
	}

	public void setListResultPoints(List<Point> listResultPoints) {
		this.listResultPoints = listResultPoints;
	}

	public CartesianChartModel getChartModel() {
		return chartModel;
	}

	public void setChartModel(CartesianChartModel chartModel) {
		this.chartModel = chartModel;
	}

	public boolean isHasHeader() {
		return hasHeader;
	}

	public void setHasHeader(boolean hasHeader) {
		this.hasHeader = hasHeader;
	}

	public String getFileSeparator() {
		return fileSeparator;
	}

	public void setFileSeparator(String fileSeparator) {
		this.fileSeparator = fileSeparator;
	}

	public int getSelectedChartType() {
		return selectedChartType;
	}

	public void setSelectedChartType(int selectedChartType) {
		this.selectedChartType = selectedChartType;
	}

	public FileData getNewData() {
		return newData;
	}

	public void setNewData(FileData newData) {
		this.newData = newData;
	}

	public Long getNewDataRowKey() {
		return newDataRowKey;
	}

	public void setNewDataRowKey(Long newDataRowKey) {
		this.newDataRowKey = newDataRowKey;
	}

	public String getOutput() {
		return output;
	}

	public void setOutput(String output) {
		this.output = output;
	}

	public boolean isShowResults() {
		return showResults;
	}

	public void setShowResults(boolean showResults) {
		this.showResults = showResults;
	}

	public FileData getRemovedData() {
		return removedData;
	}

	public void setRemovedData(FileData removedData) {
		this.removedData = removedData;
	}

	public Panel getPanelParameters() {
		return panelParameters;
	}

	public void setPanelParameters(Panel panelParameters) {
		this.panelParameters = panelParameters;
	}

	public String getObjTest() {
		return objTest;
	}

	public void setObjTest(String objTest) {
		this.objTest = objTest;
	}

	public boolean isShowParameters() {
		return showParameters;
	}

	public void setShowParameters(boolean showParameters) {
		this.showParameters = showParameters;
	}

	public Integer getSelectedMethod() {
		return selectedMethod;
	}

	public void setSelectedMethod(Integer selectedMethod) {
		this.selectedMethod = selectedMethod;
	}

	public Integer getSelectedParameter() {
		return selectedParameter;
	}

MachineLearning-Web/MachineLearning-Web/MachineLearging/WebContent/pages/inicial/inicial.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:f="http://java.sun.com/jsf/core"      
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
      
	<ui:composition template="/templates/template.xhtml">
      
      	<ui:define name="scripts">
      		<script type="text/javascript">
      			$(document).ready(function(){
      				
      				$('html').click(function(){
      					dataTable.saveCell($('.ui-editable-column.ui-cell-editing'));
      				});
      				
      				prepareToShow();
      				updateParameters();
      				
      			});
      		</script>
      	</ui:define>
      
    	<ui:define name="title">
    		<h:outputText value="#{msg['pagina.inicial.titulo']}"></h:outputText>
    	</ui:define>
    	
    	<ui:define name="content">
    	<h:form id="form">
    		<div class="superiorPanel">
	    		<p:toolbar>
	    			<p:toolbarGroup align="left">
	    				<h:panelGrid columns="3" cellpadding="5">
				    		<p:selectOneMenu id="selectMethod" value="#{mainBean.selectedMethod}">
				    			<f:selectItem itemLabel="Select Method" itemValue="-1" />	
				    			<f:selectItems value="#{autocompleteBean.listMethods}" />
				    			<p:ajax event="change" update="selectMethod outputPanelParameters" listener="#{mainBean.populateParameters}"/>
				    		</p:selectOneMenu>
				    		<p:selectOneMenu value="#{mainBean.selectedParameter}">
				    			<f:selectItem itemLabel="Dados do RU" itemValue="1" />
				    		</p:selectOneMenu>
				    		<p:commandButton value="Run" action="#{mainBean.execute}" icon="ui-icon-circle-triangle-e" update="chartPanel"/>
	    				</h:panelGrid>
	    			</p:toolbarGroup>
	    		</p:toolbar>
	    		
	    		<p:outputPanel id="outputPanelParameters" autoUpdate="true">
		    		<p:panel id="panelParameters" header="Parameters" binding="#{mainBean.panelParameters}" rendered="#{mainBean.showParameters}" style="min-height:40px;">
		    		</p:panel>
	    		</p:outputPanel>
    		</div>
    		<div class="leftPanel">
    			<p:panel header="Data" styleClass="panel">
    				<center style="border-bottom:1px solid #CDCDCD;margin-bottom: 10px;">
	    				<p:commandButton value="Load File" type="button" onclick="fileDialog.show();" icon="ui-icon-arrowthickstop-1-n" style="margin:10px 0;"/>
    				</center>
    				
    				<p:panelGrid id="newDataInput" columns="3" style="width:100%">
    					<h:panelGroup>
		    				<p:inputText id="valor1" value="#{mainBean.newData.value1}" style="width:100%;" />
		    				<p:watermark value="valor1" for="valor1" />
    					</h:panelGroup>
    					<h:panelGroup>
		    				<p:inputText id="valor2" value="#{mainBean.newData.value2}" style="width:100%;" />
		    				<p:watermark value="valor2" for="valor2" />
    					</h:panelGroup>
    					<p:commandButton icon="ui-icon-circle-plus" action="#{mainBean.addData}" update="newDataInput dataTable" />
    				</p:panelGrid>
    				
    				<br />
    				
    				<p:dataTable 
   						id="dataTable"
    					value="#{mainBean.listDataModel}"
    					var="fileData"
    					rowKey="#{fileData.id}"
    					editable="true"
    					emptyMessage="No data loaded."
    					editMode="cell"
    					widgetVar="dataTable"
    					scrollable="true"
    					scrollHeight="250"
    					style="border:1px solid #E1E1E1">
    					
    					<f:facet name="header">
    						<h:outputText value="#{mainBean.file == null ? 'File' : mainBean.fileNameTruncated}"/>
    					</f:facet>
    					
    					<p:column headerText="#{mainBean.nameColumn1 == null || mainBean.nameColumn1.equals('') ? 'Value 1' : mainBean.nameColumn1}" style="width:40%;">
    						<p:cellEditor>
    							<f:facet name="output">
		    						<h:outputText value="#{fileData.value1}" />
    							</f:facet>
    							<f:facet name="input">
		    						<p:inputText value="#{fileData.value1}" style="width:91%;" />
    							</f:facet>
    						</p:cellEditor>
    					</p:column>
    					
    					<p:column headerText="#{mainBean.nameColumn2 == null || mainBean.nameColumn2.equals('') ? 'Value 2' : mainBean.nameColumn2}" style="width:40%;">
    						<p:cellEditor>
    							<f:facet name="output">
		    						<h:outputText value="#{fileData.value2}" />
    							</f:facet>
    							<f:facet name="input">
		    						<p:inputText value="#{fileData.value2}" style="width:91%;" />
    							</f:facet>
    						</p:cellEditor>
    					</p:column>
    					
    					<p:column style="width:20%;">
    						<p:commandButton icon="ui-icon-circle-close" action="#{mainBean.removeData}" update="dataTable" styleClass="noBG">
    							<f:setPropertyActionListener target="#{mainBean.removedData}" value="#{fileData}" />
    						</p:commandButton>
    					</p:column>
    					
    					<f:facet name="footer">
    						<h:outputText value="Input data"/>
    					</f:facet>
    					
    					<p:ajax event="cellEdit" listener="#{mainBean.onCellEdit}" update="@this" ></p:ajax>
    				</p:dataTable>
    			</p:panel>
    		</div>
    		<div class="rightPanel">
    			<p:panel id="chartPanel" header="Results" styleClass="panel">
    				<p:outputPanel rendered="#{mainBean.showResults}">
	    				<p:accordionPanel>
	    					<p:tab title="Charts">
				    			<div>
				    				<p:selectOneButton value="#{mainBean.selectedChartType}">
				    					<p:ajax event="change" update="chartPanel" />
				    					<f:selectItem itemLabel="Bar" itemValue="0" />
				    					<f:selectItem itemLabel="Line" itemValue="1" />
				    				</p:selectOneButton>
				    			</div>
				    			<p:outputPanel id="chartPanel">
				    				<p:barChart id="barChart" value="#{mainBean.chartModel}" animate="true" zoom="true" title="Bar Chart" rendered="#{mainBean.selectedChartType == 0}" />
				    				<p:lineChart id="lineChart" value="#{mainBean.chartModel}" animate="true" zoom="true" title="Linear Chart" rendered="#{mainBean.selectedChartType == 1}" />
				    			</p:outputPanel>
	    					</p:tab>
	    					<p:tab title="Output">
    							<p:inputTextarea readonly="true" value="#{mainBean.output}" cols="100" autoResize="false" rows="15" />
	    					</p:tab>
	    				</p:accordionPanel>
    				</p:outputPanel>
    			</p:panel>
    		</div>
    		<div class="clear"> </div>
    	</h:form>
    	</ui:define>
    	
    	<ui:define name="dialogs">
			<p:dialog header="Load File" widgetVar="fileDialog" resizable="false" draggable="false" modal="true" footer="Only .csv files">
		    	<h:form enctype="multipart/form-data">  
		    		<h:panelGrid columns="2">
		    			<p:panelGrid columns="2">
			    			<h:outputText value="File with header: " />
			    			<p:selectBooleanButton offLabel="No" onLabel="Yes" value="#{mainBean.hasHeader}" />
			    			<h:outputText value="Column separator: " />
			    			<p:inputText value="#{mainBean.fileSeparator}" style="width:40px;" />
						    <p:fileUpload value="#{mainBean.file}" mode="simple" />
						    <p:commandButton value="Ok" ajax="false" icon="ui-icon-check" action="#{mainBean.loadFile}" />  
		    			</p:panelGrid>
		    		</h:panelGrid>
				</h:form>  
			</p:dialog>    	
    	</ui:define>
    	
    	<ui:define name="remoteCommands">
    	
    		<p:remoteCommand name="prepareToShow" action="#{mainBean.prepareToShow}" />
    		<p:remoteCommand name="updateParameters" update=":form:panelParameters" />
    	
    	</ui:define>
    	      
    </ui:composition>
      
</html>